// Rendering and diffing. Like analyze.mjs: pure, no clock, no filesystem —
// the run's own `date` field is the only notion of time.

import { rivalCounts } from './advice.mjs';

const citedIds = (run) =>
  new Set((run?.results ?? []).filter((r) => r.status === 'cited').map((r) => r.id));

export function diffRuns(previous, next) {
  const before = citedIds(previous);
  const after = citedIds(next);
  const gained = [...after].filter((id) => !before.has(id)).sort();
  const lost = [...before].filter((id) => !after.has(id)).sort();
  const baseline = previous == null;

  return {
    gained,
    lost,
    baseline,
    // A first run has nothing to compare against: everything would look like a
    // gain, and the ops channel would get a wall of noise on day one.
    changed: !baseline && (gained.length > 0 || lost.length > 0),
  };
}

const percent = (value) => `${(value * 100).toFixed(1)}%`;

const bucketRows = (buckets) =>
  Object.entries(buckets)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([key, b]) => `| ${key} | ${b.cited} | ${b.mentioned} | ${b.absent} |`)
    .join('\n');

const STATUS_ICON = { cited: '✅', mentioned: '➖', absent: '❌' };

export function citedProperties(run) {
  const counts = {};
  for (const result of run.results ?? []) {
    const properties = new Set(
      (result.attempts ?? []).flatMap((attempt) => attempt.citedDomains ?? []),
    );
    for (const property of properties) counts[property] = (counts[property] ?? 0) + 1;
  }
  return counts;
}

export function renderReport({ run, previous, manual }) {
  const diff = diffRuns(previous, run);
  const lines = [];

  lines.push('# AI visibility — mi-code.pl');
  lines.push('');
  lines.push('<!-- Generated by scripts/ai-visibility/run.mjs. Do not edit by hand. -->');
  lines.push('');
  lines.push(`**Run:** ${run.date} · **Model:** ${run.model} · **Calls:** ${run.calls}`);
  lines.push(`**Cited share:** ${percent(run.summary.citedShare)}`);
  lines.push('');

  if (diff.baseline) {
    lines.push('First run — no previous measurement to compare against.');
  } else if (diff.changed) {
    if (diff.gained.length) lines.push(`**Newly cited:** ${diff.gained.join(', ')}`);
    if (diff.lost.length) lines.push(`**No longer cited:** ${diff.lost.join(', ')}`);
  } else {
    lines.push('No change in the set of cited prompts since the previous run.');
  }
  lines.push('');

  lines.push('## By language');
  lines.push('');
  lines.push('| lang | cited | mentioned | absent |');
  lines.push('|---|---|---|---|');
  lines.push(bucketRows(run.summary.byLang));
  lines.push('');

  lines.push('## By kind');
  lines.push('');
  lines.push('| kind | cited | mentioned | absent |');
  lines.push('|---|---|---|---|');
  lines.push(bucketRows(run.summary.byKind));
  lines.push('');

  const properties = citedProperties(run);
  if (Object.keys(properties).length) {
    lines.push('## Which property was cited');
    lines.push('');
    lines.push('| property | prompts |');
    lines.push('|---|---|');
    for (const [property, count] of Object.entries(properties).sort(([a], [b]) => a.localeCompare(b))) {
      lines.push(`| ${property} | ${count} |`);
    }
    lines.push('');
  }

  lines.push('## Prompts');
  lines.push('');
  lines.push('| | prompt | lang | target |');
  lines.push('|---|---|---|---|');
  for (const result of run.results) {
    lines.push(
      `| ${STATUS_ICON[result.status] ?? '?'} | ${result.id} | ${result.lang} | ${result.target ?? ''} |`,
    );
  }
  lines.push('');

  lines.push('## Manual snapshot');
  lines.push('');
  if (manual) {
    lines.push(`Month: ${manual.month}`);
    lines.push('');
    lines.push('| crawler | hits |');
    lines.push('|---|---|');
    for (const [bot, hits] of Object.entries(manual.crawlers ?? {})) {
      lines.push(`| ${bot} | ${hits} |`);
    }
    lines.push('');
    lines.push('| referrer | sessions |');
    lines.push('|---|---|');
    for (const [source, sessions] of Object.entries(manual.referrals ?? {})) {
      lines.push(`| ${source} | ${sessions} |`);
    }
    lines.push('');
    if (manual.engines?.length) {
      lines.push('| engine | prompt | status |');
      lines.push('|---|---|---|');
      for (const row of manual.engines) {
        lines.push(`| ${row.engine} | ${row.id} | ${row.status} |`);
      }
      lines.push('');
    }
  } else {
    lines.push('There is no manual snapshot for this month yet.');
    lines.push('');
  }

  lines.push('## What this does not measure');
  lines.push('');
  lines.push('- Gemini is **not ChatGPT**. One engine gives a trend line for how findable and');
  lines.push('  citable the site is, not a share of all AI answers.');
  lines.push('- Grounding through an API does not rank the same way the engine\'s web UI does.');
  lines.push('- GA4 referrals only count visitors who accepted cookies, so that figure is a floor.');
  lines.push('- A single run proves nothing. Only the series does.');
  lines.push('');

  return lines.join('\n');
}

const TELEGRAM_LIMIT = 4096;

const bucketTotal = (bucket) => bucket.cited + bucket.mentioned + bucket.absent;

// Russian counts in three: 1 вызов, 2–4 вызова, 5+ вызовов — except the teens,
// where 11–14 take the plural despite ending in 1–4. A full sweep is 54, so the
// naive `${n} вызовов` was wrong on the one number this line prints most.
export function plural(count, one, few, many) {
  const abs = Math.abs(count) % 100;
  if (abs >= 11 && abs <= 14) return many;
  const last = abs % 10;
  if (last === 1) return one;
  if (last >= 2 && last <= 4) return few;
  return many;
}

export function renderTelegramReport(run, previous, advice) {
  const results = run.results ?? [];
  const cited = results.filter((item) => item.status === 'cited').length;
  const lines = [];

  lines.push('📊 AI-видимость mi-code.pl');
  lines.push(
    `Свип ${run.sweep ?? '?'} · ${run.date} · ${run.calls} ${plural(run.calls, 'вызов', 'вызова', 'вызовов')}`,
  );
  lines.push('');

  const head = `Процитированы: ${cited} из ${results.length} (${percent(run.summary.citedShare)})`;
  if (previous) {
    const before = (previous.results ?? []).filter((item) => item.status === 'cited').length;
    // Guarded like every other cross-run access: a previous run file written by
    // an older schema would otherwise throw here — after main() has written the
    // run file and reset partial.json, but before the commit step, losing days
    // of measurement on a runner that cannot replay them.
    lines.push(`${head} — было ${before} из ${(previous.results ?? []).length} (${percent((previous.summary ?? {}).citedShare ?? 0)})`);
  } else {
    lines.push(head);
  }

  const langs = Object.entries(run.summary.byLang ?? {})
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([lang, bucket]) => `${lang} ${bucket.cited}/${bucketTotal(bucket)}`);
  if (langs.length) lines.push(`По языкам: ${langs.join(' · ')}`);

  const kinds = run.summary.byKind ?? {};
  const kindParts = [];
  if (kinds.brand) kindParts.push(`Бренд ${kinds.brand.cited}/${bucketTotal(kinds.brand)}`);
  if (kinds.category) kindParts.push(`Категория ${kinds.category.cited}/${bucketTotal(kinds.category)}`);
  if (kindParts.length) lines.push(kindParts.join(' · '));

  const diff = diffRuns(previous, run);
  if (!diff.baseline) {
    lines.push('');
    lines.push(`Появились: ${diff.gained.length ? diff.gained.join(', ') : '—'}`);
    lines.push(`Пропали: ${diff.lost.length ? diff.lost.join(', ') : '—'}`);
  }

  const rivals = Object.entries(rivalCounts(run))
    .filter(([domain]) => domain !== 'unknown')
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .slice(0, 3)
    .map(([domain, count]) => `${domain} (${count})`);
  if (rivals.length) {
    lines.push('');
    lines.push(`Цитируют вместо нас: ${rivals.join(' · ')}`);
  }

  // The header is never sacrificed: advice lines are appended one at a time and
  // the first one that would breach the limit ends the list.
  const header = lines.join('\n');
  if (!advice.length) return header;

  const opened = `${header}\n\nЧто делать:`;
  let text = opened;
  for (const item of advice) {
    const next = `${text}\n• ${item.text}`;
    if (next.length > TELEGRAM_LIMIT) break;
    text = next;
  }
  return text === opened ? header : text;
}
