/**
 * IndexNow ping.
 *
 * ChatGPT's search citations lean on Bing's index, and Bing discovers a static site on its own
 * schedule. IndexNow lets the deploy announce what changed the moment it ships. The key is
 * public by design — it is served from the site itself so the receiving engine can verify that
 * whoever submitted the URLs controls the host.
 *
 * Run after a build: `node scripts/indexnow.mjs [dist-dir]`
 */
import { readFile, readdir } from 'node:fs/promises';

const ENDPOINT = 'https://api.indexnow.org/indexnow';

/** IndexNow accepts at most this many URLs in one request. */
const MAX_URLS = 10000;

/**
 * Pull every `<loc>` out of a sitemap. Deliberately a regex rather than an XML parser: the
 * sitemap is generated by `scripts/prerender.mjs` in this same repo, so its shape is known,
 * and this keeps the deploy free of another dependency.
 */
export function extractUrls(xml) {
  const matches = xml.matchAll(/<loc>([\s\S]*?)<\/loc>/g);
  return Array.from(matches, (match) => match[1].trim()).filter(Boolean);
}

/**
 * The key lives in the deployed site as `<key>.txt`, which is both how the engine verifies
 * ownership and the single source of truth for its value — nothing to configure in CI, and no
 * way for a constant somewhere to drift out of sync with the file that is actually served.
 */
export function keyFromFileNames(names) {
  const match = names.find((name) => /^[a-f0-9]{8,128}\.txt$/i.test(name));
  return match ? match.replace(/\.txt$/i, '') : null;
}

export function buildPayload(urls, key) {
  if (!Array.isArray(urls) || urls.length === 0) {
    throw new Error('IndexNow: no urls to submit');
  }
  if (!key) {
    throw new Error('IndexNow: missing key');
  }

  const { origin, host } = new URL(urls[0]);

  return {
    host,
    key,
    keyLocation: `${origin}/${key}.txt`,
    urlList: urls.slice(0, MAX_URLS)
  };
}

export async function submit(payload, fetchImpl = fetch) {
  const response = await fetchImpl(ENDPOINT, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
    body: JSON.stringify(payload)
  });
  return response.status;
}

const invokedDirectly = process.argv[1] && process.argv[1].endsWith('indexnow.mjs');

if (invokedDirectly) {
  const distDir = process.argv[2] ?? 'dist';

  try {
    const key = keyFromFileNames(await readdir(distDir));
    const urls = extractUrls(await readFile(`${distDir}/sitemap.xml`, 'utf8'));
    const payload = buildPayload(urls, key);
    const status = await submit(payload);
    console.log(`IndexNow: submitted ${payload.urlList.length} urls, HTTP ${status}`);
  } catch (error) {
    // A search-engine ping is never worth failing a deploy over.
    console.warn(`IndexNow: skipped — ${error.message}`);
  }
}
